[package]
name = "schematic-supertest"
version = "0.1.1"
edition = "2021"
description = "Authoring primitives for Schematic Supertests"
readme = "README.md"
repository = "https://github.com/schematic-tech/supertest-rust"
license = "MIT OR Apache-2.0"
rust-version = "1.85"
publish = ["crates-io"]

[lib]
name = "schematic"

[dependencies]
schematic-supertest-macros = { path = "macros", version = "=0.1.1" }

[workspace]
members = ["macros"]
